# Original: train_Real_HAT_GAN_SRx4_finetune_from_mse_model.yml
# general settings
name: HAT_GAN_BASELINE_CALGAN_L1_V2
model_type: AesopESRGANArtifactsDisMoEV2Model
scale: 4
num_gpu: auto
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRGANModel ----------------- #
queue_size: 180

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: BicubicDataset
    h5_file: datasets/train-df2k.h5

    gt_size: 128
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 24
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: Set5
    type: EvalImagePairedDataset
    dataset: set5
    h5_file: datasets/test-sisr.h5
    gt_size: 256

  val_2:
    name: Set14
    type: EvalImagePairedDataset
    dataset: set14
    h5_file: datasets/test-sisr.h5
    gt_size: 256

# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 32
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# Mixture of discriminators
network_d:
  type: MOD
  num_in_ch: 3
  num_feat: 128
  num_expert: 4

path:
  pretrain_network_g: pretrained/HAT_SRx4_ImageNet-pretrain.pth    # or a path to a model
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  use_amp: true
  use_compile: false
  high_order_degradation: false

  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [600000]
    gamma: 1

  total_iter: 30000
  warmup_iter: -1 #no warm up

  # NOTE: https://github.com/2minkyulee/AESOP-Auto-Encoded-Supervision-for-Perceptual-Image-Super-Resolution/blob/main/AESOP/options/train/AESOP/train_RealWorld_AESOP.yml

  pixel_opt:
    type: L1Loss
    loss_weight: 10.0
    reduction: mean
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 0.5
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  # tau annealing for MOD Gumbel-Softmax routing
  tau_anneal:
    tau_start: 2.0
    tau_end: 0.5
    anneal_iters: 30000

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 1e3
  save_img: true
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    niqe:
      type: calculate_niqe
      crop_border: 4
      better: lower  # the lower, the better
    lpips:
      type: calculate_lpipsv2
      crop_border: 4
      test_y_channel: false
      better: lower
    dists:
      type: calculate_dists
      crop_border: 4
      test_y_channel: false
      better: lower
    topiq:
      type: calculate_topiq
      crop_border: 4
      test_y_channel: false
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
